spring.application.name=finance
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finance
spring.datasource.username=finance
spring.datasource.password=finance
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration